[project]
name = "lithium"
version = "0.1.0"
requires-python = ">=3.12"
<<<<<<< HEAD

dependencies = [
  "django==5.1.2",
  "django-allauth[openid,socialaccount]==65.0.2",
  "django-debug-toolbar==4.4.6",
  "django-crispy-forms==2.3",
  "crispy-bootstrap5==2024.10",
  "gunicorn==23.0.0",
  "psycopg[binary]==3.2.3",
  "whitenoise==6.7.0",
  "python-decouple==3.8",
  "dj-database-url>=3.0.0",
  "asgiref==3.8.1",
  "certifi==2022.12.7",
  "cffi==1.15.1",
  "charset-normalizer==3.0.1",
  "cryptography==39.0.1",
  "defusedxml==0.7.1",
  "idna==3.4",
  "oauthlib==3.2.2",
  "packaging==23.1",
  "pycparser==2.21",
  "PyJWT==2.6.0",
  "python3-openid==3.2.0",
  "requests==2.28.2",
  "requests-oauthlib==1.3.1",
  "sqlparse==0.4.3",
  "urllib3==1.26.14"
=======
dependencies = [
  "django ~=5.1",
  "django-allauth[openid,socialaccount] ~=65.2",
  "django-debug-toolbar ~=4.4",
  "crispy-bootstrap5 ~=2024.10",
  "gunicorn ~=23.0",
  "psycopg[binary] ~=3.2",
  "whitenoise ~=6.7",
  "python-decouple>=3.8",
>>>>>>> 67e56f3 (initial commit)
]

[dependency-groups]
dev = [
<<<<<<< HEAD
  "typing_extensions==4.9.0"
=======
  "typing_extensions ~=4.12",
>>>>>>> 67e56f3 (initial commit)
]
